LOCAL_PATH := $(call my-dir)
include $(MIUI_CLEAR)
MIUI_PRODUCT := mione_plus
MIUI_KERNEL := $(LOCAL_PATH)/kernel

MIUI_KERNEL_BASE := 0x40200000
MIUI_KERNEL_CMDLINE := console=null androidboot.hardware=mione
MIUI_KERNEL_PAGESIZE := 2048

MIUI_PRODUCT_ROOT := $(LOCAL_PATH)/root
MIUI_DEVICE_CONFIG := $(LOCAL_PATH)/device.conf

TARGET_USE_PIXEL_FORMAT_BGR565 := true
include $(MIUI_RECOVERY)
