LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_RECOVERY_EXECTABLES := fix_permissions
LOCAL_RECOVERY_EXECTABLES += parted
LOCAL_RECOVERY_EXECTABLES += sdparted
LOCAL_RECOVERY_EXECTABLES += nandroid-md5.sh
LOCAL_RECOVERY_EXECTABLES += killrecovery.sh
LOCAL_RECOVERY_EXECTABLES += root_device 
RECOVERY_EXECTABLES := $(addprefix $(TARGET_ROOT_OUT)/sbin/, $(LOCAL_RECOVERY_EXECTABLES))
$(RECOVERY_EXECTABLES): $(LOCAL_INSTALLED_MODULE)
	@echo "copy $@ "
	@mkdir -p $(dir $@)
	@rm -rf $@
	@cp -rf src/utilities/$(notdir $@) $(dir $@)

ALL_DEFAULT_INSTALLED_MODULES += $(RECOVERY_EXECTABLES)


#Add by 搞机圈－老杨 root_device
include $(CLEAR_VARS)
LOCAL_FORCE_STATIC_EXECUTABLE : true 
LOCAL_MODULE := root_device 
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE_TAGS := eng 
LOCAL_SRC_FILES := extend_command.c 
LOCAL_STATIC_LIBRARIES := libc libcrecovery  
include $(BUILD_EXECUTABLE)

#
#include $(CLEAR_VARS)
#LOCAL_MODULE := fix_permissions
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
#LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
#LOCAL_SRC_FILES := $(LOCAL_MODULE)
#include $(BUILD_PREBUILT)
#
#include $(CLEAR_VARS)
#LOCAL_MODULE := parted
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
#LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
#LOCAL_SRC_FILES := $(LOCAL_MODULE)
#include $(BUILD_PREBUILT)
#
#include $(CLEAR_VARS)
#LOCAL_MODULE := sdparted
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
#LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
#LOCAL_SRC_FILES := $(LOCAL_MODULE)
#include $(BUILD_PREBUILT)
#
## include $(CLEAR_VARS)
## LOCAL_MODULE := e2fsck
## LOCAL_MODULE_TAGS := optional
## LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
## LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
## LOCAL_SRC_FILES := $(LOCAL_MODULE)
## include $(BUILD_PREBUILT)
#
## include $(CLEAR_VARS)
## LOCAL_MODULE := tune2fs
## LOCAL_MODULE_TAGS := optional
## LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
## LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
## LOCAL_SRC_FILES := $(LOCAL_MODULE)
## include $(BUILD_PREBUILT)
#
## include $(CLEAR_VARS)
## LOCAL_MODULE := mke2fs
## LOCAL_MODULE_TAGS := optional
## LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
## LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
## ifeq ($(BOARD_MKE2FS),)
## LOCAL_SRC_FILES := $(LOCAL_MODULE)
## else
## LOCAL_SRC_FILES := ../../../$(BOARD_MKE2FS)
## endif
## include $(BUILD_PREBUILT)
#
#ifneq ($(TARGET_RECOVERY_FSTAB),)
#  BOARD_RECOVERY_RFS_CHECK := $(shell grep rfs $(TARGET_RECOVERY_FSTAB))
#else
#  BOARD_RECOVERY_RFS_CHECK := $(shell grep rfs $(TARGET_DEVICE_DIR)/recovery.fstab)
#endif
#
#ifneq ($(BOARD_RECOVERY_RFS_CHECK),)
#include $(CLEAR_VARS)
#LOCAL_MODULE := fat.format
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
#LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
#LOCAL_SRC_FILES := $(LOCAL_MODULE)
#include $(BUILD_PREBUILT)
#endif
#
#include $(CLEAR_VARS)
#LOCAL_MODULE := nandroid-md5.sh
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
#LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
#LOCAL_SRC_FILES := nandroid-md5.sh
#include $(BUILD_PREBUILT)
#
#include $(CLEAR_VARS)
#LOCAL_MODULE := killrecovery.sh
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
#LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
#LOCAL_SRC_FILES := killrecovery.sh
#include $(BUILD_PREBUILT)
#
