LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := ChromeBookmarksSyncAdapter
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := ChromeBookmarksSyncAdapter.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := ChromeBookmarksSyncAdapter.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := FaceLock
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := FaceLock.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := FaceLock.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Gmail
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := Gmail.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := Gmail.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Gmail_Data
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := Gmail.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH  := $(TARGET_OUT_DATA)/app
LOCAL_SRC_FILES := Gmail.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleBackupTransport
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := GoogleBackupTransport.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := GoogleBackupTransport.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleCalendarSyncAdapter
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := GoogleCalendarSyncAdapter.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := GoogleCalendarSyncAdapter.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleContactsSyncAdapter
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := GoogleContactsSyncAdapter.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := GoogleContactsSyncAdapter.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleLoginService
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := GoogleLoginService.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := GoogleLoginService.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GooglePartnerSetup
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := GooglePartnerSetup.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := GooglePartnerSetup.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleServicesFramework
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := GoogleServicesFramework.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := GoogleServicesFramework.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Maps
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := Maps.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := Maps.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Maps_Data
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := Maps.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH  := $(TARGET_OUT_DATA)/app
LOCAL_SRC_FILES := Maps.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := NetworkLocation
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := NetworkLocation.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := NetworkLocation.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Talk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := Talk.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := Talk.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Talk_Data
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := Talk.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH  := $(TARGET_OUT_DATA)/app
LOCAL_SRC_FILES := Talk.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Vending
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := Vending.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := Vending.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Vending_Data
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := Vending.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH  := $(TARGET_OUT_DATA)/app
LOCAL_SRC_FILES := Vending.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := VoiceSearch
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := VoiceSearch.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := VoiceSearch.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := VoiceSearch_Data
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := VoiceSearch.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH  := $(TARGET_OUT_DATA)/app
LOCAL_SRC_FILES := VoiceSearch.apk
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)
